### ISSUE TITLE
Dropbox/Google Drive integration

### ISSUE THREAD

**Issue by lars-derichter** [c9/vfs#22]
It would be really nice to be able to use the same api's with Dropbox and/or Google Drive...

**Comment by creationix** [comment]
I started a prototype of this.  Let me dig up my code...

**Comment by creationix** [comment]
https://github.com/c9/vfs-google-drive

**Comment by lars-derichter** [comment]
Thanks a lot. I will have a look at it.

**Comment by creationix** [comment]
Keep in mind that Google Drive doesn't have the concept of trees.  There are special documents called folders and documents can contain parents or children.  I've mapped this to the directory structure that vfs expects best I can, but there are cases where the abstraction won't work. For example, a "folder" in google drive, can have multiple files with the exact same title (filename).  readdir will list both, but any path-based request will only be able to map one of them.  Also path to id mapping is somewhat expensive, but I cache where I can in this code.  Eventually I had planned to use the changes feed to smartly invalidate the cache so that it can be longer lived, but never invalid.
